# Generated by Django 2.2.15 on 2020-08-06 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrator', '0006_auto_20200706_0454'),
        ('company', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinator',
            fields=[
                ('name', models.CharField(max_length=120, null=True)),
                ('admissionNumber', models.IntegerField(primary_key=True, serialize=False)),
                ('yearOfGraduation', models.IntegerField()),
                ('rollNumber', models.IntegerField()),
                ('course', models.CharField(choices=[('BT', 'B. Tech'), ('MT', 'M. Tech'), ('MC', 'MCA'), ('MS', 'M. Sc'), ('MB', 'MBA')], default='BT', max_length=2)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.Branch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('name', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('dateOfVisit', models.DateField(null=True)),
                ('status', models.CharField(choices=[('Waiting', 'waiting'), ('Denied', 'denied'), ('Accepted', 'accepted')], default='Waiting', max_length=8)),
                ('existing_status', models.CharField(choices=[('Alive', 'Alive'), ('Dead', 'Dead')], default='Alive', max_length=8)),
                ('branchesAllowed', models.CharField(blank=True, default='', max_length=2000, null=True)),
                ('CGPA', models.FloatField(default=7.0)),
                ('companyID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.Details')),
            ],
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('type_of_announcement', models.CharField(choices=[('Broadcasting', 'Broadcast'), ('Eligible', 'Eligible_ones')], default='Broadcasting', max_length=20)),
                ('announcementid', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('datePublished', models.DateField(default=django.utils.timezone.now)),
                ('text', models.CharField(max_length=500)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.Details')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
