# Generated by Django 3.0.8 on 2020-07-05 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20200705_0606'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coordinator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('name', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('dateOfVisit', models.DateField(null=True)),
                ('status', models.CharField(choices=[('Waiting', 'waiting'), ('Denied', 'denied'), ('Accepted', 'accepted')], default='Waiting', max_length=8)),
                ('branchesAllowed', models.CharField(blank=True, default='', max_length=2000, null=True)),
                ('CGPA', models.FloatField(default=7.0)),
                ('companyID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.Details')),
            ],
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('type_of_announcement', models.CharField(choices=[('Broadcasting', 'Broadcast'), ('Eligible', 'Eligible_ones')], default='Broadcasting', max_length=20)),
                ('announcementid', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('datePublished', models.DateTimeField(default=django.utils.timezone.now)),
                ('text', models.CharField(max_length=500)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.Details')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
