# Generated by Django 3.1.4 on 2021-01-02 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator', '0002_announcement_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='user',
            field=models.IntegerField(),
        ),
    ]
