# Generated by Django 3.0.7 on 2020-06-30 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator', '0002_companies'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='course',
            field=models.CharField(choices=[('BT', 'B. Tech'), ('MT', 'M. Tech'), ('MC', 'MCA'), ('MS', 'M. Sc'), ('MB', 'MBA')], default='BT', max_length=2),
        ),
    ]
