# Generated by Django 3.0.7 on 2020-06-30 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator', '0003_companies_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companies',
            name='course',
        ),
    ]
