# Generated by Django 3.0.8 on 2020-07-07 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator', '0003_auto_20200706_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='existing_status',
            field=models.CharField(choices=[('Alive', 'Alive'), ('Dead', 'Dead')], default='Alive', max_length=8),
        ),
    ]
