# Generated by Django 3.0.7 on 2020-06-30 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator', '0006_auto_20200630_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='CGPA',
            field=models.FloatField(default=7.0),
        ),
    ]
