# Generated by Django 3.0.7 on 2020-06-30 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_auto_20200630_1451'),
        ('coordinator', '0007_companies_cgpa'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacedStudents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admissionNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coordinator.Companies')),
            ],
        ),
    ]
