# Generated by Django 3.0.7 on 2020-06-30 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator', '0008_placedstudents'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('text', models.CharField(max_length=100000)),
            ],
        ),
    ]
