# Generated by Django 3.0.7 on 2020-06-30 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator', '0009_announcements'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='status',
            field=models.CharField(choices=[('W', 'waiting'), ('D', 'denied'), ('A', 'accepted')], default='W', max_length=8),
        ),
        migrations.AlterField(
            model_name='companies',
            name='dateOfVisit',
            field=models.DateField(null=True),
        ),
    ]
