# Generated by Django 3.0.7 on 2020-07-01 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator', '0010_auto_20200630_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='status',
            field=models.CharField(choices=[('Waiting', 'waiting'), ('Denied', 'denied'), ('Accepted', 'accepted')], default='Waiting', max_length=8),
        ),
        migrations.DeleteModel(
            name='PlacedStudents',
        ),
    ]
