# Generated by Django 3.0.7 on 2020-07-01 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator', '0014_updatestudents'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UpdateStudents',
        ),
    ]
