# Generated by Django 3.0.8 on 2020-07-03 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator', '0016_companies_companyid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companies',
            name='CTC',
        ),
        migrations.RemoveField(
            model_name='companies',
            name='user',
        ),
    ]
