# Generated by Django 3.0.8 on 2020-07-03 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator', '0017_auto_20200703_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='branchesAllowed',
            field=models.CharField(blank=True, default='', max_length=2000, null=True),
        ),
    ]
