# Generated by Django 3.0.8 on 2020-07-04 08:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20200704_0805'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coordinator', '0018_auto_20200703_0543'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('type_of_announcement', models.CharField(choices=[('Broadcasting', 'Broadcast'), ('Eligible', 'Eligible_ones')], default='Broadcasting', max_length=20)),
                ('announcementid', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('datePublished', models.DateTimeField(default=django.utils.timezone.now)),
                ('text', models.CharField(max_length=500)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.Details')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Announcements',
        ),
    ]
