# Generated by Django 3.0.7 on 2020-06-30 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='branchCode',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='branch',
            name='course',
            field=models.CharField(choices=[('BT', 'B. Tech'), ('MT', 'M. Tech'), ('MC', 'MCA'), ('MS', 'M. Sc'), ('MB', 'MBA')], default='BT', max_length=2),
        ),
        migrations.AlterField(
            model_name='branch',
            name='branch',
            field=models.CharField(default='CSE', max_length=50),
        ),
    ]
