# Generated by Django 3.0.7 on 2020-07-01 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_auto_20200630_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course', models.CharField(default='CSE', max_length=50, primary_key=True, serialize=False)),
            ],
        ),
    ]
