# Generated by Django 3.0.8 on 2020-07-03 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='branchCode',
            field=models.CharField(default='cse', max_length=10),
        ),
    ]
