# Generated by Django 3.0.8 on 2020-07-06 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0005_auto_20200703_0550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.Course'),
        ),
    ]
