# Generated by Django 3.0.8 on 2020-07-06 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter', models.URLField(null=True)),
                ('facebook', models.URLField(null=True)),
                ('instagram', models.URLField(null=True)),
                ('gplus', models.URLField(null=True)),
                ('linkedin', models.URLField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='HomePage',
        ),
        migrations.AddField(
            model_name='photosnitw',
            name='caption',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
