# Generated by Django 2.2.15 on 2020-08-06 07:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkForTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1000)),
                ('dateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('otherInstructions', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='SelectedStudents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selectedStudents', models.CharField(default='None qualified', max_length=2000)),
                ('name', models.CharField(max_length=40)),
                ('round', models.CharField(choices=[('D', 'D')], default='D', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploadFile', models.FileField(null=True, upload_to='images/Documents/Company/Schedule', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('name', models.CharField(default='name', max_length=10)),
                ('user', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LoginDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploadFile', models.FileField(null=True, upload_to='images/Documents/Company/LoginDetails', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('name', models.CharField(default='name', max_length=10)),
                ('user', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('name', models.CharField(default='ABC', max_length=120, primary_key=True, serialize=False)),
                ('websiteLink', models.CharField(max_length=120, null=True)),
                ('hrDetails', models.CharField(max_length=2000, null=True)),
                ('address', models.CharField(max_length=2000, null=True)),
                ('emailId', models.EmailField(max_length=254, null=True)),
                ('phoneNumber', models.CharField(max_length=15, null=True)),
                ('mobileNumber', models.CharField(max_length=15, null=True)),
                ('sector', models.CharField(blank=True, default='', max_length=2000, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('category', models.CharField(blank=True, default='', max_length=2000, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('jobDesignation', models.CharField(max_length=120, null=True)),
                ('jobType', models.CharField(blank=True, default='', max_length=200, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('workLocation', models.CharField(max_length=1000, null=True)),
                ('tentativeDOJ', models.DateField(null=True)),
                ('roundsDetails', models.CharField(blank=True, default='', max_length=2000, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('numberOfRounds', models.CharField(max_length=10, null=True)),
                ('otherInfo', models.CharField(max_length=1000, null=True)),
                ('salaryDetails_btech', models.CharField(default='0', max_length=1000, null=True)),
                ('salaryDetails_mtech', models.CharField(default='0', max_length=1000, null=True)),
                ('salaryDetails_otherPG', models.CharField(default='0', max_length=1000, null=True)),
                ('salaryDetails_PhD', models.CharField(default='0', max_length=1000, null=True)),
                ('minOffers', models.CharField(default='0', max_length=10, null=True)),
                ('trainingPeriod', models.CharField(default='0', max_length=10, null=True)),
                ('stipulatedBond', models.CharField(default='0', max_length=10, null=True)),
                ('stipendDetails_BTech', models.CharField(default='0', max_length=1000, null=True)),
                ('stipendDetails_MTech', models.CharField(default='0', max_length=1000, null=True)),
                ('stipendDetails_OtherPG', models.CharField(default='0', max_length=1000, null=True)),
                ('duration_UG', models.CharField(default='0', max_length=1000, null=True)),
                ('duration_PG', models.CharField(default='0', max_length=1000, null=True)),
                ('user', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContactCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('mailid', models.EmailField(max_length=254)),
                ('message', models.CharField(max_length=2000)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
