# Generated by Django 3.0.8 on 2020-07-05 06:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkForTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1000)),
                ('dateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('otherInstructions', models.CharField(max_length=10000)),
            ],
        ),
        migrations.AddField(
            model_name='details',
            name='minOffers',
            field=models.CharField(default='0', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='details',
            name='user',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='details',
            name='address',
            field=models.CharField(max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='emailId',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='hrDetails',
            field=models.CharField(max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='jobDesignation',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='mobileNumber',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='numberOfRounds',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='otherInfo',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='phoneNumber',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='stipulatedBond',
            field=models.CharField(default=0, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='tentativeDOJ',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='trainingPeriod',
            field=models.CharField(default='0', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='websiteLink',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='workLocation',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.CreateModel(
            name='SelectedStudents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selectedStudents', models.CharField(default='None qualified', max_length=20000)),
                ('name', models.CharField(max_length=40)),
                ('round', models.CharField(choices=[('D', 'D')], default='D', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploadFile', models.FileField(null=True, upload_to='test/Documents/Company/Schedule', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('name', models.CharField(default='name', max_length=10)),
                ('user', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LoginDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploadFile', models.FileField(null=True, upload_to='test/Documents/Company/LoginDetails', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('name', models.CharField(default='name', max_length=10)),
                ('user', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
