# Generated by Django 3.1.4 on 2021-01-02 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20210101_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='user',
        ),
    ]
