# Generated by Django 3.0.8 on 2020-07-07 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_contactcompany'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='duration_PG',
            field=models.CharField(default='0', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='duration_UG',
            field=models.CharField(default='0', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='salaryDetails_PhD',
            field=models.CharField(default='0', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='salaryDetails_btech',
            field=models.CharField(default='0', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='salaryDetails_mtech',
            field=models.CharField(default='0', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='salaryDetails_otherPG',
            field=models.CharField(default='0', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='stipendDetails_BTech',
            field=models.CharField(default='0', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='stipendDetails_MTech',
            field=models.CharField(default='0', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='stipendDetails_OtherPG',
            field=models.CharField(default='0', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='stipulatedBond',
            field=models.CharField(default='0', max_length=10, null=True),
        ),
    ]
