# Generated by Django 3.0.8 on 2020-07-03 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20200702_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='address',
            field=models.CharField(max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='emailId',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='hrDetails',
            field=models.CharField(max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='jobDesignation',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='minOffers',
            field=models.CharField(default='0', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='mobileNumber',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='numberOfRounds',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='otherInfo',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='phoneNumber',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='stipulatedBond',
            field=models.CharField(default=0, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='trainingPeriod',
            field=models.CharField(default='0', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='websiteLink',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='workLocation',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
