# Generated by Django 3.0.8 on 2020-07-04 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20200704_0805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selectedstudents',
            name='uploadFile',
        ),
        migrations.AddField(
            model_name='selectedstudents',
            name='selectedStudents',
            field=models.CharField(default='None qualified', max_length=20000),
        ),
        migrations.AlterField(
            model_name='selectedstudents',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
