# Generated by Django 3.0.8 on 2020-07-04 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_auto_20200704_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkForTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1000)),
                ('dateTime', models.DateTimeField()),
                ('otherInstructions', models.CharField(max_length=10000)),
            ],
        ),
    ]
