# Generated by Django 3.0.8 on 2020-07-04 12:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_linkfortest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkfortest',
            name='dateTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
