# Generated by Django 2.1.1 on 2018-09-01 21:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrator', '0002_branch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('datePublished', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('branches', models.ManyToManyField(to='administrator.Branch')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue', models.CharField(max_length=100)),
                ('time', models.DateTimeField()),
                ('text', models.CharField(max_length=500)),
                ('datePublished', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('admissionNumber', models.IntegerField(primary_key=True, serialize=False)),
                ('yearOfGraduation', models.IntegerField()),
                ('rollNumber', models.IntegerField()),
                ('CGPA', models.FloatField()),
                ('course', models.CharField(choices=[('BT', 'B. Tech'), ('MT', 'M. Tech'), ('MC', 'MCA'), ('MS', 'M. Sc'), ('MB', 'MBA')], default='BT', max_length=2)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.Branch')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'student_user',
            },
        ),
        migrations.AddField(
            model_name='company',
            name='coordinators',
            field=models.ManyToManyField(to='student.Student'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Company'),
        ),
    ]
