# Generated by Django 3.0.8 on 2020-07-05 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator', '0002_announcement_companies'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coordinator.Companies')),
                ('user', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyApplicants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placementStatus', models.CharField(choices=[('A', 'Applied'), ('I', 'Qualified for Interview'), ('N', 'Not applied'), ('P', 'Placed'), ('R', 'R')], default='N', max_length=2)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coordinator.Companies')),
            ],
        ),
        migrations.RemoveField(
            model_name='company',
            name='branches',
        ),
        migrations.RemoveField(
            model_name='company',
            name='coordinators',
        ),
        migrations.RemoveField(
            model_name='student',
            name='course',
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coordinator.Companies'),
        ),
        migrations.AlterField(
            model_name='student',
            name='admissionNumber',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='rollNumber',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Announcement',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.AddField(
            model_name='companyapplicants',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student'),
        ),
    ]
