# Generated by Django 3.0.8 on 2020-07-05 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_remove_resume_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='fieldOfInterest',
        ),
    ]
