# Generated by Django 3.0.7 on 2020-06-30 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
    ]
