# Generated by Django 3.0.8 on 2020-07-06 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_remove_resume_fieldofinterest'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='mobileNumber',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
