# Generated by Django 3.0.8 on 2020-07-06 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20200706_0514'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.Student'),
        ),
    ]
