# Generated by Django 3.0.7 on 2020-06-30 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_auto_20200630_0627'),
        ('student', '0002_auto_20200630_0724'),
    ]

    operations = [
    ]
