# Generated by Django 3.0.8 on 2020-07-07 09:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='picture',
            field=models.FileField(null=True, upload_to='RegisterPictures/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])]),
        ),
    ]
