# Generated by Django 3.0.8 on 2020-07-10 05:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_student_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='address',
            field=models.TextField(default='1234 main st'),
        ),
        migrations.AddField(
            model_name='resume',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='phoneNumber',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='year',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='picture',
            field=models.FileField(null=True, upload_to='RegisterPictures/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])]),
        ),
    ]
