# Generated by Django 3.0.8 on 2020-07-10 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_auto_20200710_0535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='achievements',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='education',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='resume',
            name='extraCurricular',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='projects',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='resume',
            name='relevantCourses',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='skills',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.TextField(null=True),
        ),
    ]
