# Generated by Django 3.0.7 on 2020-07-01 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator', '0013_auto_20200701_0732'),
        ('student', '0014_auto_20200701_0732'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyApplicants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placementStatus', models.CharField(choices=[('A', 'Applied'), ('I', 'Qualified for Interview'), ('R', 'Rejected from Interview'), ('P', 'Placed')], default='A', max_length=2)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Application')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coordinator.Companies')),
            ],
        ),
    ]
