# Generated by Django 3.0.7 on 2020-07-01 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0016_auto_20200701_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyapplicants',
            name='placementStatus',
            field=models.CharField(choices=[('A', 'Applied'), ('I', 'Qualified for Interview'), ('N', 'Not applied'), ('P', 'Placed')], default='N', max_length=2),
        ),
    ]
