# Generated by Django 3.0.7 on 2020-07-01 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0018_auto_20200701_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='course',
        ),
    ]
