# Generated by Django 3.0.8 on 2020-07-04 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0020_auto_20200702_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='admissionNumber',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='rollNumber',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
